#!/bin/bash

jupyter contrib nbextension install --only-config
jupyter nbextensions_configurator enable --user
jupyter nbextension enable splitcell/splitcell
jupyter nbextension enable hide_input_all/main
